name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    services:
      minio:
        image: lazybit/minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: miniopass
        options: >-
          --health-cmd="curl -f http://localhost:9000/minio/health/live"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 9000:9000
          - 9001:9001

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.11.1"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
